// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20230816154238_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BookImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfPages")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfPurchases")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummaryDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Author = "Kate Douglas Wiggin",
                            BookImage = "rebecca",
                            Description = "The novel depicts an unnamed young woman who impetuously marries a wealthy widower, before discovering that both he and his household are haunted by the memory of his late first wife, the title character.",
                            ISBN = "8764-212314551",
                            NumberOfPages = 143,
                            NumberOfPurchases = 23,
                            Price = 20.989999999999998,
                            Quantity = 5,
                            SummaryDescription = "Rebecca is a 1938 Gothic novel written by English author Daphne du Maurier.",
                            Title = "Rebecca",
                            Year = 1938
                        },
                        new
                        {
                            ID = 2,
                            Author = "Jane Austen",
                            BookImage = "emma",
                            Description = "It is set in the fictional country village of Highbury and the surrounding estates of Hartfield, Randalls and Donwell Abbey, and involves the relationships among people from a small number of families.",
                            ISBN = "978-1853260285",
                            NumberOfPages = 1036,
                            NumberOfPurchases = 11,
                            Price = 15.59,
                            Quantity = 31,
                            SummaryDescription = "Emma is a novel written by Jane Austen",
                            Title = "Emma",
                            Year = 1815
                        },
                        new
                        {
                            ID = 3,
                            Author = "Octavia E. Butler",
                            BookImage = "kindred",
                            Description = "Kindred (1979) is a novel by American writer Octavia E. Butler that incorporates time travel and is modeled on slave narratives.  Widely popular, it has frequently been chosen as a text by community-wide reading programs and book organizations, and for high school and college courses.",
                            ISBN = "0-385-15059-8",
                            NumberOfPages = 264,
                            NumberOfPurchases = 3,
                            Price = 25.59,
                            Quantity = 1,
                            SummaryDescription = "Kindred (1979) is a novel by American writer Octavia E. Butler that incorporates time travel and is modeled on slave narratives",
                            Title = "Kindred ",
                            Year = 1979
                        },
                        new
                        {
                            ID = 4,
                            Author = "Chris Frazer Smith",
                            BookImage = "atonement",
                            Description = "Set in three time periods, 1935 England, Second World War England and France, and present-day England, it covers an upper-class girl's half-innocent mistake that ruins lives, her adulthood in the shadow of that mistake, and a reflection on the nature of writing.",
                            ISBN = "0-224-06252-2",
                            NumberOfPages = 371,
                            NumberOfPurchases = 77,
                            Price = 17.390000000000001,
                            Quantity = 14,
                            SummaryDescription = "Atonement is a 2001 British metafictional novel written by Ian McEwan.",
                            Title = "Atonement ",
                            Year = 2001
                        },
                        new
                        {
                            ID = 5,
                            Author = "Chimamanda Ngozi Adichie",
                            BookImage = "americanah",
                            Description = "The novel traces Ifemelu's life in both countries, threaded by her love story with high school classmate Obinze. It was Adichie's third novel.",
                            ISBN = "978-0-307-96212-6",
                            NumberOfPages = 608,
                            NumberOfPurchases = 1,
                            Price = 35.200000000000003,
                            Quantity = 2,
                            SummaryDescription = "Americanah is a 2013 novel by the Nigerian author Chimamanda Ngozi Adichie, for which Adichie won the 2013 U.S",
                            Title = "Americanah",
                            Year = 2013
                        },
                        new
                        {
                            ID = 6,
                            Author = "John Steinbeck",
                            BookImage = "ofmiceandmen",
                            Description = "Published in 1937, it narrates the experiences of George Milton and Lennie Small, two displaced migrant ranch workers, who move from place to place in California in search of new job opportunities during the Great Depression in the United States.",
                            ISBN = "978-0-307-96212-6",
                            NumberOfPages = 107,
                            NumberOfPurchases = 42,
                            Price = 5.2000000000000002,
                            Quantity = 3,
                            SummaryDescription = "Of Mice and Men is a novella written by John Steinbeck.",
                            Title = "Of Mice and Men",
                            Year = 1937
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
